image: nixos/nix

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

ci:
  tags:
    - x86_64-linux
  script:
    - nix-shell -p git
    - nix-shell
    - cabal update
    - cabal build -w ghc-9.2.4 ghc-debug-brick ghc-debug-common ghc-debug-convention ghc-debug-client ghc-debug-stub
    - cabal test -w ghc-9.2.4
    - cabal build -w ghc-9.4.2 ghc-debug-brick ghc-debug-common ghc-debug-convention ghc-debug-client ghc-debug-stub
    - cabal test -w ghc-9.4.2

pages:
  script:
    - nix-build -A site --arg ci true -o site-out --option trusted-public-keys "mpickering.cachix.org-1:COxPsDJqqrggZgvKG6JeH9baHPue8/pcpYkmcBPUbeg= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" --option substituters "https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/ https://mpickering.cachix.org"
    - mkdir -p public
    - cp -r site-out/* public/
  artifacts:
    paths:
      - public

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
